[package]
name = "moqtail-cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
moqtail-core = { path = "../moqtail-core" }
rumqttc = "0.24"

[dependencies.clap]
version = "4"
features = ["derive"]

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
