[workspace]
members = [
    "xtask",
    "crates/moqtail-core",
    "crates/moqtail-cli",
    "bindings/python",
    "bindings/js",
]
default-members = [
    "xtask",
    "crates/moqtail-core",
    "crates/moqtail-cli",
    "bindings/js",
]
resolver = "2"
