[package]
name = "moqtail-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
pest = "2"
pest_derive = "2"
serde_json = "1"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "matcher"
harness = false

