[package]
name = "moqtail-js"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
moqtail-core = { path = "../../crates/moqtail-core" }
napi = { version = "2", features = ["napi6"] }
napi-derive = "2"
